### ISSUE TITLE
youtube无法播放视频

### ISSUE THREAD

**Issue by sunnoy** [yumin9822/zmirror-docker#2]
能打开网页

**Comment by yumin9822** [comment]
用的是什么系统？推荐ubuntu

**Comment by seramat** [comment]
同样的问题。作者说
“
与requests 2.12 的兼容性问题, (requests是zmirror依赖的一个核心库)
requests 2.12设置了非常严格的url格式规范, 对不规范的url会直接拒绝发起请求

而youtube视频的url很不巧长得像这样:
https://a--b--f3456.googlevideo.com/blahblah
域名中包含横线(-), 不符合requests 2.12 的规范, 会拒绝发出请求, zmirror就无法工作了.

目前没有很好的解决办法, 临时的办法是将requests版本限制为 2.11及以下

如果是用一键脚本部署的, 请重新部署一次, 加入了对requests的版本限制”
请问使用@yumin9822一键部署的如何解决这个问题？

**Comment by yumin9822** [comment]
现在pip安装requests时引用了原作者的requirements。
https://raw.githubusercontent.com/aploium/zmirror/master/requirements.txt
